name: Ourcraft
version: 0.1
author: Vincent Qi
main: main.Ourcraft
commands:
  debug:
    description: Debug Command
    usage: /debug <?args>
  ourinventory:
    description: Opens Our Inventory
    usage: /ourinventory